// Emit dist/_headers, deriving the noindex block from SITE_URL.
//
// This used to be a static file in public/, which meant the claim "both robots
// and noindex derive from SITE_URL" was only half true — robots.txt is an
// endpoint, _headers was hand-maintained. Attaching the real domain would have
// needed someone to remember a second edit, from a phone, months later.
//
// Now the flip is genuinely one change: point SITE_URL at the real host.
//
//   node scripts/emit-headers.mjs      (runs after astro build)

import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const SITE_TS = 'src/lib/site.ts';
const OUT = 'dist/_headers';

const src = readFileSync(SITE_TS, 'utf8');
const match = src.match(/export const SITE_URL\s*=\s*['"]([^'"]+)['"]/);
if (!match) {
  console.error(`could not read SITE_URL from ${SITE_TS}`);
  process.exit(1);
}
const siteUrl = match[1];
const isPreview = new URL(siteUrl).hostname.endsWith('.pages.dev');

const blocks = [
  `# Generated by scripts/emit-headers.mjs — do not edit dist/_headers by hand.`,
  `# Derived from SITE_URL = ${siteUrl}`,
  ``,
];

if (isPreview) {
  blocks.push(
    `# Preview host. This header is the ONLY thing keeping the site out of the`,
    `# index, and that is deliberate: robots.txt allows crawling so the crawler`,
    `# can actually fetch a page and read this line. Blocking the crawl would`,
    `# leave URLs indexable-by-discovery instead of definitively excluded.`,
    `/*`,
    `  X-Robots-Tag: noindex, nofollow`,
    `  X-Content-Type-Options: nosniff`,
    `  Referrer-Policy: strict-origin-when-cross-origin`,
    ``
  );
} else {
  blocks.push(
    `/*`,
    `  X-Content-Type-Options: nosniff`,
    `  Referrer-Policy: strict-origin-when-cross-origin`,
    ``,
    `# Never indexable regardless of host.`,
    `/rtl-test/*`,
    `  X-Robots-Tag: noindex, nofollow`,
    ``,
    `/admin/*`,
    `  X-Robots-Tag: noindex, nofollow`,
    ``
  );
}

blocks.push(
  `/fonts/*`,
  `  Cache-Control: public, max-age=31536000, immutable`,
  ``,
  `/_astro/*`,
  `  Cache-Control: public, max-age=31536000, immutable`,
  ``
);

if (!existsSync('dist')) {
  console.error('no dist/ — run the build first');
  process.exit(1);
}

writeFileSync(OUT, blocks.join('\n'));
console.log(
  `  wrote ${OUT} — ${isPreview ? 'PREVIEW: site-wide noindex' : 'PRODUCTION: indexable'}`
);
